* How to use Plug 
- ref: https://hexdocs.pm/phoenix/plug.html
  - For example, without using Plug, if we want to validate something in an controller, we will use nested blocks of code. 
    After using Plug, we could replace those nested block of code wit ha flattened series of plug transformations.
  - The ~halt(conn)~ the is key. It tells Plug that the next plug should not be invoked.
    
** How authentication is implemented in Rumbl application as plug
- In Rumbl, authentication is implemented with two plugs:
  - One is type of function plug, ~def authenticate_user(conn, _opts)~. It is used in ~user_controller~ module for action [:index, :show].
    #+begin_src elixir :file lib/rumbl_web/router.ex
      plug :authenticate_user when action in [:index, :show]
    #+end_src
  - Another is type of module plug, the ~RumblWeb.Auth~. It is used in pipeline ~browser~.
    #+begin_src elixir :file lib/rumbl_web/controllers/auth.ex
      pipeline :browser do
        plug :accepts, ["html"]
        ...
        # our own plug
        plug RumblWeb.Auth
      end
    #+end_src
- The module plug makes sure the conn's ~current_user~ property exist with value equals to ~user~ or ~nil~. This is for every connection.
- The function plug makes sure request to UserController's index and show path must contains ~user~.

** Controller are module plug to be used as [[https://hexdocs.pm/phoenix/controllers.html#action-fallback][action fallback]]
- Action fallback allows us to centralize error handling code in plugs which are called when a controller action fails to return a ~%Plug.Conn{}~ struct.

    
* Pipelines and Plugs 
- Pipelines are a series of plugs that can be attached to specific scopes.
- Routes are defined inside scopes and scopes may pipe through multiple pipelines.
- The router invokes a pipeline on a route defined *within* a scope. Routes outside of a scope have no pipelines.
** How to create pipelines
- Define custom pipelines anywhere in the router module.

* How to redirect a request 
- For example, we want to redirect user after he/she created account.
  #+begin_src elixir
    def create(conn, %{"user" => user_params}) do
      case Accounts.register_user(user_params) do
        # Do login if we insert the newly registered user in database.
        {:ok, user} ->
          conn
          |> RumblWeb.Auth.login(user)
          |> put_flash(:info, "#{user.name} created!")
          |> redirect(to: Routes.user_path(conn, :index))

        {:error, %Ecto.Changeset{} = changeset} ->
          render(conn, "new.html", changeset: changeset)
      end
    end
  #+end_src
  - *Notice*: Route helper function ~Routes.user_path~ is used to make sure the redirect path is correct.


* Controller 
** How to pass multiple values when render a template 
- For one value, we could use key: value pair as the third argument. Such as: ~render(conn, "show.html", messenger: messenger)~.
- For multiple values, we could use ~Plug.Conn.assign~:
  #+begin_src elixir
    def show(conn, %{"messenger" => messenger}) do
      conn
      |> assign(:messenger, messenger)
      |> assign(:receiver, "Dweezil")
      |> render("show.html")
    end
  #+end_src


* Ecto 
** How to create models (the data in DB)
- use phx.gen.schema
  #+begin_src sh
    mix phx.gen.schema User users name:string email:string \
        number_of_pets:integer
  #+end_src
  - This will generate two files, one is the ~user.ex~ model with schema, another is the ~xxx_create_user.exs~ which contains the migration for our DB.
  - After modifying them to perfectly suit our need, we run ~mix ecto.migrate~.
    
** About changeset 
- What is changeset?
  - A changeset defines some contains/validation for our data.
  - We use it by ~import Ecto.Changeset~ and it defines a lot of useful functions.
  - Use that module, we could validate our data which we want to insert into our db.
  - It will return a result with true or false, plus the changes (our validated/filtered data).
- How template and changeset are binded?
  - A changeset could be passed into template like this: ~render(conn, "new.html", changeset: changeset)~.
- What is the differences between validation and constraint
  - Validation executed before touching the db. And constraint rely on the database.
  - Therefore, validation happends before constraint.    

* Channels    
** About channels
- Components 
  1. Endpoint, in your Phoenix app's *Endpoint* module
     #+begin_src elixir :file lib/rumbl_web/endpoint.ex
       socket "/socket", RumblWeb.UserSocket,
         websocket: true,
         longpoll: false
     #+end_src
  2. Socket Handler
     1) On client side, we establish socket connection to the route
        #+begin_src elixir :file assets/js/socket.js
          import {Socket} from "phoenix"

          let socket = new Socket("/socket", {
            params: {token: window.userToken},
            logger: (kind, msg, data) => {console.log(`${kind}: ${msg}`, data)}
          })

          export default socket
        #+end_src
        - The point here is to create websocket connection to connect to ~/socket~ defined in RumblWeb.Endpoint module.

     2) On server side, inside RumblWeb.UserSocket module
        #+begin_src elixir :file rumbl_web/channels/user_socket.ex
          defmodule RumblWeb.UserSocket do
            use Phoenix.Socket

            channel "videos:*", RumblWeb.VideoChannel

            def connect(_params, socket, _connect_info) do
              {:ok, socket}
            end

            def id(_socket) do
              nil
            end
          end
        #+end_src
        - Whenever a client sends a message whose topic starts with "videos:", it will be routed to our ~VideoChannel~.
        - Implemented two callbacks.
         
  3. Define ~VideoChannel~ module to manage messages.
     #+begin_src elixir :file rumbl_web/channels/video_channel.ex
       defmodule RumblWeb.VideoChannel do
         use RumblWeb, :channel

         # "videos:" <> video_id will match all topics starting with "videos:"
         # and assign the rest of the topic to the video_id variable
         def join("videos:" <> video_id, _params, socket) do
           {:ok, assign(socket, :video_id, String.to_integer(video_id))}
         end
       end
     #+end_src
     - Let clients to join a given topic.

  4. Get the client and server talking
     1) Create socket and join a channel.
        #+begin_src js
        socket.connect()
        let vidChannel = socket.channel("videos:" + videoId)

        vidChannel.join()
          .receive("ok", resp => console.log("joined the video channel", resp))
          .receive("error", reason => {
            console.log("join failed", reason)
          })
        #+end_src

     2) Sending and Receiving events 
        - On client 
          #+begin_src js
            vidChannel.on("ping", ({count} => console.log("PING", count)))
          #+end_src

        - On server 
          #+begin_src elixir
            defmodule RumblWeb.VideoChannel do
              use RumblWeb, :channel

              # "videos:" <> video_id will match all topics starting with "videos:"
              # and assign the rest of the topic to the video_id variable
              def join("videos:" <> video_id, _params, socket) do
                # {:ok, assign(socket, :video_id, String.to_integer(video_id))}

                :timer.send_interval(5000, :ping)
                {:ok, socket}
              end

              def handle_info(:ping, socket) do
                count = socket.assigns[:count] || 1

                push(socket, "ping", %{count: count})
                {:noreply, assign(socket, :count, count + 1)}
              end
            end
          #+end_src
          - Our server send to "videos:" channel a message for every 5 second.
          - ~handle_info~ callback is invoked whenever an elixir message reaches the channel.
           
           

- In general,
  - On server
    - Define a socket module and mount it as a socket endpoint. Inside this socket module:
      - Implement ~id/1~ and ~connect/3~ methods.
      - Define channel routes with its channel module.
    - Define a channel module 
      - Define how client join a given topic by implementing ~join/3~.
      - Handle incoming events by using 
        - ~handle_in~
        - ~handle_out~
        - ~handle_info~
  - On client
    - Import socket, connect to an socket endpoint defined by server.
    - Create channel using ~socket.channel~. After that join the channel(~someChannel.join~) and receive message (~someChannel.receive~).
    - Handle channel's event like ~someChannel.on("someEvent", callback)~.
       
** TODO General steps recorded from Rumbl application 
In this application, we are using channels to build video annotation in real time.

1. Confirm we could establish the websocket connection. Here, we prepare the client and server for the channel.
   1) Use JavaScript to build Phoenix client.
      - Create a Video module in ~assets/js/video.js~.
      - Initialize it from ~assets/js/app.js~.
   2) In ~assets/js/user-socket.js~, we create socket and export this module.
   3) The ~rumbl_web/channels/user_socket.ex~ defines the ~UserSocket~ module which serves as the starting point for all socket connections.

   At this point, you should be able to connect to socket.

2. Create the channel 
   1) Define the channel the client will join: match a topic with a channel module.
      #+begin_src elixir
        channel "videos:*", RumblWeb.VideoChannel
      #+end_src

   2) Implement the VideoChannel module. It will alow connections through ~join~ function.
      #+begin_src elixir
        def join("videos:" <> video_id, _params, socket) do
          ...
        end
      #+end_src
      - Notice the pattern matching: it will match all topics starting with "videos:", and assign the rest of the topic to the ~video_id~.

   3) Modify the ~video.js~ to 
      - Create channel from the socket and give it our topic.
      - Join the channel with ~receive~.

3. Sending and receiving events (socket(different endpoint) --> channel(different topic) --> different event)
   1) On server side, in our ~RumblWeb.VideoChannel~ module, we implement handle_in, handle_out, and handle_info. 
      - Conceptually, we are taking a socket and returning a transformed socket.
      - We could ~push~ some event.
   2) On client side, receive that message with ~channel.on(event, callback)~.
   3) Modify server side
      - Handle the specific event(new_annotation) and broadcast it to all connected socket with event type: "new_annotation".
   4) Modify client side
      - When user click a button, we push annotation to channel with "new_annotation" event type with payload.
      - Listen on "new_annotation" event and render the received message.
      - Render annotation is done by creating a div with content and append that div to some element.

      So, user click, push event --> server, receive it and broadcast it back to all client --> client handle event and display.

4. Socket authentication
   1) Expose the token to the client side in "lib/rumbl_web/templates/layout/app.html.heex".
      #+begin_src html
        <script>window.userToken = "<%= assigns[:user_token] %>"</script>
      #+end_src

   2) Add the ~:user_token~ to ~conn.assigns~ whenever we have a current user.
   3) Pass the user token to the ~Socket~ constructor on the client
   4) Update RumblWeb.UserSocket module using pattern matching for ~connect/2~ function.

5. Persisting annotation















* Other what/how
** How to construct js code for channels 
- Our js code will follow these patterns 
  - Use "let Something = {}" to include all the code in it, then export it as "export default Something".
  - It will contain "init" method as constructor.
  - Other functions will be binded to it as "this.someFunction".

